/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PlayerRatingsIndexRouteImport } from './routes/player-ratings.index'
import { Route as PlayerRatingsSlugRouteImport } from './routes/player-ratings.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRatingsIndexRoute = PlayerRatingsIndexRouteImport.update({
  id: '/player-ratings/',
  path: '/player-ratings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRatingsSlugRoute = PlayerRatingsSlugRouteImport.update({
  id: '/player-ratings/$slug',
  path: '/player-ratings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/player-ratings/$slug': typeof PlayerRatingsSlugRoute
  '/player-ratings/': typeof PlayerRatingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/player-ratings/$slug': typeof PlayerRatingsSlugRoute
  '/player-ratings': typeof PlayerRatingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/player-ratings/$slug': typeof PlayerRatingsSlugRoute
  '/player-ratings/': typeof PlayerRatingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/perfil'
    | '/reset-password'
    | '/player-ratings/$slug'
    | '/player-ratings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/perfil'
    | '/reset-password'
    | '/player-ratings/$slug'
    | '/player-ratings'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/perfil'
    | '/reset-password'
    | '/player-ratings/$slug'
    | '/player-ratings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  PerfilRoute: typeof PerfilRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  PlayerRatingsSlugRoute: typeof PlayerRatingsSlugRoute
  PlayerRatingsIndexRoute: typeof PlayerRatingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player-ratings/': {
      id: '/player-ratings/'
      path: '/player-ratings'
      fullPath: '/player-ratings/'
      preLoaderRoute: typeof PlayerRatingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player-ratings/$slug': {
      id: '/player-ratings/$slug'
      path: '/player-ratings/$slug'
      fullPath: '/player-ratings/$slug'
      preLoaderRoute: typeof PlayerRatingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  PerfilRoute: PerfilRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  PlayerRatingsSlugRoute: PlayerRatingsSlugRoute,
  PlayerRatingsIndexRoute: PlayerRatingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
